### ISSUE TITLE
Makefile - Electrotest

### ISSUE THREAD

**Issue by agnon** [tojo0084/Lab6#12]
Kanske skriva om Makefile för electrotest att länka mot biblioteken där de blir installerade i /usr/local/{lib,include} ?

**Comment by tojo0084** [comment]
Det verkar vara meningen att man för makefile install ska använda biblioteken där de bli installerade, men inte för makefile all.

Citat från kurssidan med redovisning del 2:
"
all, För att bygga både programmet och biblioteken där biblioteken läggs i en egen katalog, lib,  under den man är jus nu, tex /home/bl/electro/lib/. Här ska programmet länkas för att använda de lokala biblioteken. OBS! Ni får inte temporärt ändra libsökvägarna i LD_LIBRARY_PATH!

install. Här kopierar du både programmet och biblioteken till lämpliga kataloger (tex /usr/bin/ och /usr/lib/) och länkar så att programmet använder de publika biblioteken.
"

**Comment by agnon** [comment]
mkay. Men i det stora hela blir det ju samma grej att vi installerar våra bibliotek i /usr/local exempelvis. Och sedan länkar mot dessa när electrotest byggs. Electrotest kommer ju då automagiskt med ldconfig att fungera efter att det kopierats till typ /usr/local/bin.

Detta tycker jag återspeglar lite mer hur det vanligtvis går till (man installerar sina bibliotek, bygger sedan applikationer mot/med dessa), kontra att electrotest skall bygga biblioteken och vara den som ansvarar för att de installeras på lämpligt ställe...

Tankar?

**Comment by tojo0084** [comment]
Personligen tycker jag att uppgiften egentligen borde gå ut på att electrotest inte ska bygga biblioteken, d.v.s. att electrotest makefile ska skrivas som om källkoden inte finns tillgänglig i samma projekt, utan det enda electrotest borde förutsätta är att någon annan redan har installerat vissa .so-bibliotek till /usr/local/bin

Det är väl så du menar också tror jag, och även det som menas i uppgiftens "makefile install" under del 2.

Dock är detta en kurs och då kan man inte bara resonera i termer om hur man normalt sett vill/brukar göra i verkligheten utan då måste man också försöka tolka uppgiften enligt kraven i redovisningen, och min tolkning är att makefile all i del 2 avser programmet electrotest ("bygga både programmet och biblioteken").
Observera plural i ordet "bibliotekeN" som ska byggas i makefile all.
Makefile "lib" bygger det egna biblioteKet men när man i makefile "all" ska länka mot flera lokala bibliotek "i en egen katalog, lib,  under den man är jus nu, tex /home/bl/electro/lib/" tolkar jag det som att makefile för elecrotest ska bygga även de olika biblioteken.

Men jag kanske har misstolkat vad det står i kravet på redovisning?

**Comment by tojo0084** [comment]
Jag har nu ställt en fråga på kursens forum. Fyll gärna på i den tråden (eller skapa en ny) med fler frågeställningar om ni  tycker något är otydligt.

**Comment by agnon** [comment]
Det verkade ju som vi fick medhåll av Björne, trots ett något tunt svar. Men det sista han skriver att båda förslagen funkar verkade ju lovande samtidigt som han uppdaterade infon i uppgiften men inte så pass att det återspeglar det du frågade och fick medhåll på. Han missuppfattade säkert frågan...jag tyckte det var solklart dock :)

**Comment by tojo0084** [comment]
Ja jag önskar att han hade svarat ännu tydligare.
Det står fortfarande att en makefile ska byggas och det där om att "alla bibliotek ska kompileras" kan tolkas som att makefile för electrotest även ska bygga biblioteken. 
Samtidigt skriver han att "det är ok med bägge dina förslag".

Jag föreslår att vi använder fyra makefiles som i princip är helt oberoende av varandra, med det undantaget att (för att slippa komplettera uppgiften om vi missförstått) vi från electrotest makefile anropar övriga tre makefiles dvs att följande fil:
[Lab_6_ROOT]/electrotest/Makefile
anropar följande tre (om vi ska fortsätta med nuvarande katalogstruktur):
../libpower/Makefile
../libresistance/Makefile
../libcomponent/Makefile
De tre makefilerna ovan bör i så fall skapa sina respektive .so-filer inklusive att kopiera dem till både [Lab_6_ROOT]/electrotest/lib (för regeln "all") och till  /usr/local/lib (för regeln "install")

En nackdel med att anropa tre makefiles enligt ovan är att det förutsätter att de ska ligga i en katalogstruktur så att ".."-sökvägen fungerar, men å andra sidan är det ju ett annat sorts antagande att man manuellt ska ha kört separata makefiler så att de tre biblioteken har blivit installerade.
Jag tycker man kan tolka Björne som att alla bibliotek ska kompileras som att han vill kunna köra ett enda make-kommando för electrotest, men sedan är det förstås bra att dela upp makefilen så att varje bibliotek ändå har en egen makefile som man bara då anropar från electrotest.

För övrigt fungerar inte projektets makefiles för mig (i branch master) förutom libcomponent.

libpower har ingen makefile.

libresistance$ make
Makefile:41: *** missing separator.  Stop.

electrotest$ make
make: *** No rule to make target '../libpower/src/power.c', needed by 'power.o'.  Stop.

**Comment by agnon** [comment]
Jag fixade till min Makefile.

hur som haver så finns det lite saker i nuvarande Makefile för electrotest som är lite tokiga. Men jag gör en pull request på ett förslag på ändring...

kram på er

**Comment by agnon** [comment]
La till ett förslag som nästan gör det vi pratat om. Den gör som tidigare att den bygger biblioteken på nytt utan att anropa de andra makefilerna.

Jag kanske är lite för nitisk men övningen går väl ändå ut på att arbeta med bibliotek och som du @tojo0084 redan sagt så bör vi "leka" att biblioteken är helt skilda från varandra. Ergo electrotest bör ju egentligen till o med länka endast mot installerade bibliotek men nu verkar det som att det i uppgiften explicit står att vi ska länka mot "dessa lokala" bibliotek. Och att det ska gå att köra electrotest redan i byggträdet mot mappen "lib". Men det sker/går alltså nu ... fast jag tycker det är konstigt :) Men vi får la snällt göra som uppgiften säger ;)
