### ISSUE TITLE
Koppling ska endast kunna vara "S" eller "P"

### ISSUE THREAD

**Issue by tojo0084** [tojo0084/Lab6#8]
Det blir fel om man skriver in en felaktigt koppling t.ex. "x" som i exemplet nedan istället för giltiga värden "S" eller "P".

Ange spänningskälla i V: 50
Ange koppling[S | P]: x
Antal komponenter: 3
Komponent 1 i Ohm: 300
Komponent 2 i Ohm: 500
Komponent 3 i Ohm: 598
Ersättningsresistans:
-1.000000 ohm
Effekt:
-2500.000000 
Ersättningsresistanser i E12-serien kopplade i serie:

type quit to exit

**Comment by tojo0084** [comment]
Buggfix i commit 
15b8a4792a355b185eddec3177cde9bd17a36d05

**Comment by agnon** [comment]
<3
