### ISSUE TITLE
Spänningsskälla ska kunna vara ett flyttal

### ISSUE THREAD

**Issue by tojo0084** [tojo0084/Lab6#9]
Programmet kräver heltal vid inmatning av spänningsskälla.
Det måste dock kunna hantera flyttal kan man konstatera p.g.a följande funktionssignatur:
float calc_power_r(float volt, float resistance)

Exempel på inmatningsfel som visar att flyttal inte fungerar:

Ange spänningskälla i V: 50.5
Input must be a value

**Comment by tojo0084** [comment]
Buggfix i commit 
e5f57372ca0efe4fdff311657b0e9ee934866b2f

**Comment by agnon** [comment]
Nice
